import type {Metadata} from "next";
import {Montserrat, Raleway} from "next/font/google";
import "./globals.css";
import React from "react";


const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["cyrillic"],
    display: "swap"
});
const raleway = Raleway({
    variable: "--font-raleway",
    subsets: ["cyrillic"],
    display: "swap"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body
            className={`${montserrat.variable} ${raleway.variable}  antialiased bg-new-main-dark font-sans`}
        >
        {children}
        </body>
        </html>
    );
}
